pipeline {
    agent any

    parameters {
        choice(
            name: 'testType',
            choices: ['smoke', 'regression', 'e2e', 'db', 'unit'],
            description: 'Выберите тип тестов'
        )
        choice(
            name: 'branch',
            choices: ['master', 'ci/add-jenkins-pipeline', 'staging', 'feature/my-feature'],
            description: 'Выберите ветку'
        )
        string(
            name: 'testSuite',
            defaultValue: '',
            description: 'Укажите test suite (например: ts001, ts002). Оставьте пустым если не нужно'
        )
        booleanParam(
            name: 'rerunFailedTests',
            defaultValue: false,
            description: 'Перезапустить только упавшие тесты'
        )
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: "${params.branch}", url: 'https://github.com/Meerzat22/Jenkins.git'
            }
        }

        stage('Run Tests') {
            steps {
                sh """
                    if [ "${params.rerunFailedTests}" = "true" ]; then
                        echo "Rerunning FAILED tests only..."
                        ./run_tests.sh --rerun-failed
                    else
                        echo "Running ${params.testType} tests on branch ${params.branch}"
                        if [ -n "${params.testSuite}" ]; then
                            ./run_tests.sh --type ${params.testType} --branch ${params.branch} --suite ${params.testSuite}
                        else
                            ./run_tests.sh --type ${params.testType} --branch ${params.branch}
                        fi
                    fi
                """
            }
        }
    }

    post {
        always {
            allure([
                results: [[path: 'build/allure-results']]
            ])
        }
        success {
            echo "Tests passed!"
        }
        failure {
            echo "Tests failed!"
        }
    }
}